# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
   build:
     docker:
       - image: circleci/rust:latest
     steps:
       - checkout
       - run: cargo build --features strict
       - run: cargo build --release --features strict
       - run: cargo test --features strict
   windows:
     docker:
       - image: circleci/rust:latest
     steps:
       - checkout
       - run: rustup target add x86_64-pc-windows-gnu
       - run: cargo build --features strict --target x86_64-pc-windows-gnu
       - run: cargo test --features strict --target x86_64-pc-windows-gnu
